keycloak:
  admin:
    user: "admin"
    password: "4IdVwfO8o8RHwcL72MVK"
  realms:
    - name: "keycloak-test"
      clients: # List of clientIds to configure for this realm
        - test-client
  instance:
    name: "keycloak_test"
  database:
    instance: "keycloak_test_db"
    name: "keycloak_test"
    user: "keycloak_test"
    password: 2zmSUUoHc5DnsPoj6Lia
  # Publish the ports for local test usage
  published_ports:
    - 9080:8080
    - 9443:8443