---
# This is for inclusion within loop
- name: print vars
  debug:
    var:  client

- name: Set client configuration path
  set_fact:
    client_config_filename: "{{keycloak.config_dir}}/{{ realm.name }}-{{client.name}}-client.json"

- name: print 
  debug:
    msg: "this is the var {{ client_config_filename }}"

- name: Read the client config file
  include_vars: 
    file: "{{ client_config_filename }}"
    name: client_config_json

- name: Print client config file
  debug:
    var: client_config_json.id 

- name: Check if client definition already exists
  command: "{{ keycloak_bin_path }}/kcadm.sh get clients/{{ client_config_json.id }} -r {{ realm.name }}"
  register: get_client_response
  ignore_errors: True
  failed_when: get_client_response.rc < 0


- name: Create client
  command: "{{ keycloak_bin_path }}/kcadm.sh create clients -r {{ realm.name }}  -f {{ client_config_filename }}"
  when: get_client_response.rc != 0

- name: Update client
  command: "{{ keycloak_bin_path }}/kcadm.sh update clients/{{ client_config_json.id }} -r {{ realm.name }}  -f {{ client_config_filename }}"
  when: get_client_response.rc == 0
